AllCops:
  DisplayCopNames: true
  Exclude:
    - vendor/**/*
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Max: 75

Metrics/LineLength:
  Max: 200

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false
